server:
  host: 0.0.0.0
  port: 9273

influxdb:
  url: "http://localhost:8086"
  token: "FqEzTQQWE8Ebup-gVeDKJeCzoP-O7nvu3KknpcvmEvSslUVUZF_ihNRnFd8FuLnZNgLD6j9WHS4c-wFx2xsbNQ=="
  org: "monitor-org"
  bucket: "metrics2"
